cc_binary(
  name = 'getippversion',
  srcs = [
    'getippversion.cpp',
  ],
  deps = [
    '//ippicv:ippicv',
  ]
)

cc_test(
  name = 'test',
  srcs = [
    'test.cpp'
  ],
  deps = [
    '//ippicv:ippicv',
  ]
)
